### ISSUE TITLE
打扰了，问几个问题

### ISSUE THREAD

**Issue by luchanan** [jiananle/vue-multi-page#1]
1、module下的同级子文件夹里面的.html文件如果有名字相同的话，会造成覆盖
2、目录结构能不能这样呢？
-module
----order
--------index
--------list
--------detail
--------confirm
----center
--------index
--------info
--------cupon
知道的话，告诉一下，谢谢

**Comment by jiananle** [comment]
1. 名字一样肯定覆盖啊，构建后也不能有两个名字一样的.html
2. 你是准备把模块下的页面都放一起吗， 我这里分的比较细的，你要放一起的话，只要修改下webpack 的配置就行
